sudo: required
services:
  - docker
before_install:
  - docker build -t unclebae/react-test -f ./client/Dockerfile.dev ./client/Dockerfile.dev ./client

script:
  - docker run unclebae/react-test npm test -- --coverage

after_success:
  - docker build -t unclebae/multi-client ./client
  - docker build -t unclebae/multi-nginx ./nginx
  - docker build -t unclebae/multi-server ./server
  - docker build -t unclebae/multi-worker ./worker 
  # Login in to the docker CLI 
  
  # Take those images and push them to docker hub 


