language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t unclebae/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run unclebae/react-test npm test -- --coverage

after_success:
  - docker build -t unclebae/multi-client ./client
  - docker build -t unclebae/multi-nginx ./nginx
  - docker build -t unclebae/multi-server ./server
  - docker build -t unclebae/multi-worker ./worker 
  # Login in to the docker CLI 
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub 
  - docker push unclebae/multi-client
  - docker push unclebae/multi-nginx
  - docker push unclebae/multi-server
  - docker push unclebae/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: ap-northeast-2a
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-northeast-2-103382364946
  bucket_path: docker-multi
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

